# TCOAAL Browser Player
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This repo is not a make project: the player is static files served straight
# out of app/, and the deploys live in .github/workflows/. What it does have is
# one compiled artifact, the native mod installer stub that app/create.html
# stamps, and building it leaves several gigabytes of build tree behind, none
# of which may ever be committed. That is what this file is for.
#
#   make stub       build the installer stub the way CI does, and prove it works
#   make clean      delete every built artifact in the tree
#   make distclean  clean + the caches and downloaded dependencies
#
# Tests are plain node scripts: node tools/test.js, tools/test-create.js,
# tools/test-mod-loader.js, tools/test-mod-apply.js, and
# tools/test-stub-stamp.js <stub>.

NODE ?= node
NPX ?= npx

STUB_CRATE := tools/desktop/user
STUB_TARGET := tools/desktop/target

ifeq ($(OS),Windows_NT)
  NODE_NAME := node.exe
  EXE := .exe
else
  NODE_NAME := node
  EXE :=
endif

STUB_BIN := $(STUB_TARGET)/release/tcoaal-mod-installer$(EXE)

# Everything a build produces. Each entry is regenerated by rebuilding, so
# removing it costs time and nothing else.
#
# The .modding/ entries are the local-only mod creator's build tree: that whole
# directory is gitignored and absent for most checkouts, which is why every
# removal below is guarded by an existence test rather than assumed.
BUILD_ARTIFACTS := \
	$(STUB_TARGET) \
	$(STUB_CRATE)/src-tauri/runtime \
	$(STUB_CRATE)/src-tauri/gen \
	tools/bin \
	stub \
	_site \
	android/build \
	android/app/build \
	worker/dist \
	.modding/tools/bin \
	.modding/tools/desktop/target \
	.modding/tools/desktop/creator/src-tauri/runtime \
	.modding/tools/desktop/creator/src-tauri/gen

# Not build output: fetched or cached, and slow to get back. distclean only.
CACHES := \
	node_modules \
	$(STUB_CRATE)/node_modules \
	.modding/tools/desktop/creator/node_modules \
	android/.gradle \
	worker/.wrangler

.PHONY: help stub clean distclean

help:
	@echo "make stub       build tools/desktop/user and check a stamped mod installs"
	@echo "make clean      delete every built artifact (build trees, staged runtime,"
	@echo "                bundle output, local stub/ and _site/)"
	@echo "make distclean  clean, plus node_modules, the Gradle cache and .wrangler"

# Mirrors .github/workflows/deploy-stubs.yml: stage this machine's Node as the
# runtime the binary embeds, build, then stamp a real .tcoaalmod into the
# result and run it. The last step is the one that catches a stub that builds
# but cannot install anything.
stub:
	cd $(STUB_CRATE) && npm install --no-audit --no-fund
	mkdir -p $(STUB_CRATE)/src-tauri/runtime
	cp "$$(command -v node)" "$(STUB_CRATE)/src-tauri/runtime/$(NODE_NAME)"
	chmod +x "$(STUB_CRATE)/src-tauri/runtime/$(NODE_NAME)" 2>/dev/null || true
	cd $(STUB_CRATE) && APPIMAGE_EXTRACT_AND_RUN=1 NO_STRIP=true \
		$(NPX) @tauri-apps/cli build
	$(NODE) tools/test-stub-stamp.js "$(STUB_BIN)"

clean:
	@for p in $(BUILD_ARTIFACTS); do \
		if [ -e "$$p" ]; then \
			printf '  rm %-52s %s\n' "$$p" "$$(du -sh "$$p" 2>/dev/null | cut -f1)"; \
			rm -rf "$$p"; \
		fi; \
	done
	@echo "Clean: no build output left in the tree."

distclean: clean
	@for p in $(CACHES); do \
		if [ -e "$$p" ]; then \
			printf '  rm %-52s %s\n' "$$p" "$$(du -sh "$$p" 2>/dev/null | cut -f1)"; \
			rm -rf "$$p"; \
		fi; \
	done
	@echo "Distclean: run 'npm install' before the next build."
